import 'package:flutter/material.dart';
import 'Models.dart' show CartItem;

class EncartaPage extends StatelessWidget {
  var cartItems = [
    CartItem(id:1, Strength: 400, Image: 'assets/blobs/Magmar.png', Name: "Magmar", Type: "Tipo: Escupe Fuego", Attacks: "Ataques: Cuerpo llama, Llamarada", Description: "Reseña: Pokémon que frecuentemente habita en volcanes activos. Su temperatura corporal es más alta que el magma, por lo que es su hábitat habitual. Su cuerpo está principalmente hecho de fuego."),
    CartItem(id:2, Strength: 400, Image: 'assets/blobs/Charizard.png', Name:"Charizard", Type: "Tipo: Fuego", Attacks: "Ataques: Giro Fuego, Anillo ígneo, Movimiento Sísmico", Description: "Reseña: Pokémon Dragón de Fuego con gran carácter. Es realmente difícil de atrapar o tener un Charizard, solo selectos entrenadores high level lo logran, y generalmente criándolos desde Charmander."),
    CartItem(id:3, Strength: 300, Image: 'assets/blobs/Jynx.png', Name:"Jynx", Type: "Tipo: Hielo, Psíquica", Attacks: "Ataques: Confusión, Beso Psíquico, Alud de Hielo", Description: "Reseña: Humanoide mujer, es un pokémon que le encanta moverse y bailar con gracia. Lo hace naturalmente, cuando camina mueve sus caderas con seducción ;). Es un pokémon que le encanta moverse y bailar con gracia.<Vive en el ártico con Santa Klauz ;)"),
    CartItem(id:4, Strength: 1000, Image: 'assets/blobs/Moltres.png', Name:"Moltres", Type: "Tipo: Fuego, Volador", Attacks: "Ataques: Fuego Control.", Description: "Reseña: Pokemón de clase legendaria difícil de avistar. Se dice que su aparición anunciará la llegada de la primavera. Su cuerpo está rodeado de fuego, lo que lo asemeja a la mitología del Fénix. Se dice que la llama de la antorcha que inaugura la Liga Pokemón, surgió de la cresta de Moltres: <<La llama que nunca se apaga>>"),
    CartItem(id:5, Strength: 1000, Image: 'assets/blobs/Zapdos.png', Name:"Zapdos", Type: "Tipo: Trueno, Volador", Attacks: "Ataques: Rayo control.", Description: "Reseña: Pokemón de clase legendaria con la habilidad de controlar la electricidad a su voluntad. La sola fricción de sus alas genera destellos, rayos y relámpagos. Muchos lo consideran la causa principal de las tormentas eléctricas. Aunque no es fácil de avistar, suele habitar en zonas de tormentas elécticas. Es conocido su recargo energético por el contacto los rayos, y su gusto por visitar plantas eléctricas."),
    CartItem(id:6, Strength: 1000, Image: 'assets/blobs/Articuno.png', Name:"Articuno", Type: "Tipo: Hielo, Volador", Attacks: "Ataques: Hielo Control, Viento Hielo", Description: "Reseña: Pokemón de clase legendaria con  la habilidad de controlar el hielo a su antojo. Vuela haciendo ondear su cola al viento, exhibiendo su magnifHieloncia. Al volar en inverno, su aleteo congela el agua presente en el aire, provocando que nieve a su paso. Es un pokemón solitario, que es capaz de provocar fuertes ventiscas para evitar hacer contacto."),
    CartItem(id:7, Strength: 400, Image: 'assets/blobs/Aerodactyl.png', Name:"Aerodactyl", Type: "Tipo: Roca, Volador", Attacks: "Ataques: Derribo, Lanzarocas, Avalancha.", Description: "Reseña: Pokémon fósil último de su clase conocido. Nunca atrapado."),
    CartItem(id:8, Strength: 190, Image: 'assets/blobs/Omanyte.png', Name:"Omanyte", Type: "Tipo: Agua", Attacks: "Ataques: Pistola Agua, Retribución.", Description: "Reseña: Su nombre proviene de los Ammonites, una clase de molúscos cefalópodos extintos ámpliamente usados en geología para la datación de rocas y delimitación de zonas estratográficas."),
    CartItem(id:9, Strength: 300, Image: 'assets/blobs/Kabutops.png', Name:"Kabutops", Type: "Tipo: Roca, Agua", Attacks: "Ataques: Roca afilada, Cascada", Description: "Reseña: Pokémon fósil evolución de Kabuto. Cuenta con grandes sables como extensiones de sus brazos. Habita cercano al agua salada dada su afinidad natural con el elemento agua."),
    CartItem(id:10, Strength: 350, Image: 'assets/blobs/Gengar.png', Name:"Gengar", Type: "Tipo: Fantasma", Attacks: "Ataques: Languetazo, Bola sombra.", Description: "Reseña: Evolución Suprema de Gastly. Generalmente viven en castillos abandonados o lugares tenebrosos. Es un pokemón high level, aunque hay numerosos casos de entrenadores high level que logran atrapar a un Gengar, las estadísticas dicen que los entrenadores high level que tienen un Gengar, generalmente lo criaron desde Gastly."),
    CartItem(id:11, Strength: 300, Image: 'assets/blobs/Haunter.png', Name:"Haunter", Type: "Tipo: Fantasma", Attacks: "Ataques: Languetazo, Bola sombra.", Description: "Reseña: El Fantasma supremo, la evolución máxima de Gastly, capaz de robar almas y atemorizar pueblos."),
    CartItem(id:12, Strength: 250, Image: 'assets/blobs/Gastly.png', Name:"Gastly", Type: "Tipo: Fantasma, Veneno", Attacks: "Ataques: Languetazo, Bomba lodo.", Description: "Reseña: El fantasma tóxico, lo que entra en contacto con él lo envena."),
    CartItem(id:13, Strength: 150, Image: 'assets/blobs/Golbat.png', Name:"Golbat", Type: "Tipo: Veneno, Volador", Attacks: "Ataques: Onda supersónica, Ataque rápido.", Description: "Reseña: Clase vampírica, evolución de Zubat, suele habitar en cuevas dada su analogía con los murciélagos. Golbat se alimenta de sangre tanto de Pokémon como de humanos y es capaz de beber más de 10 onzas (300 mililitros) de sangre de una sola vez. Es glotón y bebe tanta sangre que su tipo de sangre cambiará al de su víctima después de alimentarse. Hay algunos Golbat a los que les faltan colmillos como resultado de su intento de beber sangre de Pokémon tipo Acero."),
    CartItem(id:14, Strength: 120, Image: 'assets/blobs/Zubaat.png', Name:"Zubat", Type: "Tipo: Veneno, Volador", Attacks: "Ataques: Onda supersónica, Ataque rápido.", Description: "Reseña: Clase vampírica, suele habitar en cuevas dada su analogía con los murciélagos. Su piel es mayoritariamente azul, aunque las zonas membranosas de sus alas y orejas tienen un tono morado."),
    CartItem(id:15, Strength: 300, Image: 'assets/blobs/Electabuzz.png', Name:"Electabuzz", Type: "Tipo: Trueno, Lucha", Attacks: "Ataques: Puño eléctrico, Impactrueno.", Description: "Reseña: De clase Humanoide-Felina, es la evolución de Elekid. De su cabeza sobresalen dos antenas con las cuales genera grandes caudales de electricidad. Tiene dos fuertes brazos con los cuales dar puñetazos cargados de electricidad."),
    CartItem(id:16, Strength: 200, Image: 'assets/blobs/Elekid.png', Name:"Elekid", Type: "Tipo: Trueno", Attacks: "Ataques: Impactrueno, Giro eléctrico.", Description: "Reseña: De clase humanoide, genera corriente a partir de los dientes de enchufe tipo A que tiene en su cabeza. Es un pokemón sencible, su ánimo revolotea al presenciar una tormenta eléctrica, dado que su alimentación es principalmente de energía domiciliaria. Tiene dos fuertes brazos los cuales puede girar rápidamente cargándolos de electricidad."),
    CartItem(id:17, Strength: 1000, Image: 'assets/blobs/Mew.png', Name:"Mew", Type: "Tipo: Psíquico, Volador", Attacks: "Ataques: Bola de Poder, Volador", Description: "Reseña: Pokemón con forma de embrión, se dHielo que su ADN contiene el origen de todos los pokémon. Es un pokemón difícil de avistar, dado que puede hacerse invisible para no ser detectado. Estuvo varios milenios dormido en su proceso de hibernación."),
    CartItem(id:18, Strength: 1000, Image: 'assets/blobs/Mewtwo.png', Name:"Mewtwo", Type: "Tipo: Psíquico, Volador", Attacks: "Ataques: Bola de Poder, Volador", Description: "Reseña: De clase genética creado por el doctor Fuji se convirtió en aliado del team Rocket."),
    CartItem(id:19, Strength: 300, Image: 'assets/blobs/Hypno.png', Name:"Hypno", Type: "Tipo: Psíquico", Attacks: "Ataques: Confusión, Rayo psíquico.", Description: "Reseña: Pokémon humanoide psíquico, anda con un péndulo y en muchos casos no puede controlar su hipnotismo."),
    CartItem(id:20, Strength: 250, Image: 'assets/blobs/Drowzee.png', Name:"Drowzee", Type: "Tipo: Psíquico", Attacks: "Ataques: Confusión, Rayo psíquico.", Description: "Reseña: Lagarto humanoide psíquico con buen humor, es un pokémon sensitivo."),
    CartItem(id:21, Strength: 250, Image: 'assets/blobs/Marowak.png', Name:"Marowak", Type: "Tipo: Tierra", Attacks: "Ataques: Lanzamiento de Hueso, Bofetón, Earthquake.", Description: "Reseña: Pokémon de clase reptil bípodo evolución de Cubone, que al fusionar, su cráneo y el de su fallecida madre se fusionan, dandole mayor resistibilidad y confortabilidad en su andar. Es un pokémon solitario, son pocos los entrenadores que logran amaestrarlo."),
    CartItem(id:22, Strength: 180, Image: 'assets/blobs/Cubone.png', Name:"Cubone", Type: "Tipo: Tierra", Attacks: "Ataques: Lanzamiento de Hueso, Bofetón", Description: "Reseña: Pokémon de clase reptil bípodo, que lleva cargando en su cabeza, el cráneo de su difunta madre. Es un pokémon solitario y melancólico."),
    CartItem(id:23, Strength: 250, Image: 'assets/blobs/Hitmonlee.png', Name:"Hitmonlee", Type: "Tipo: Lucha", Attacks: "Ataques: Doble Patada, A bocajarro, Golpe roca, Demolición.", Description: "Reseña: Pokémon especialista en patadas, que gracias a su agilidad y elasticidad, puede dar hacia cualquier dirección y con un gran alcance, dado que sus piernas tienen forma de resorte. Al estirarse, incluso pueden doblar su altura. Posee un gran equilibrio y sus pies son duros como el diamante. Es realmente difícil de ver a un maestro pokémon que tenga uno. Generalmente son maestros pokémon con habilidades en el combate cuerpo a cuerpo."),
    CartItem(id:24, Strength: 200, Image: 'assets/blobs/Hitmonchan.png', Name:"Hitmonchan", Type: "Tipo: Lucha", Attacks: "Ataques: Puño Incremento, A bocajarro, Golpe roca.", Description: "Reseña: Boxeador innato conocido como el maestro de los puños, dada la velocidad y fuerza con que puede lanzarlos. Es capaz de noquear a casi cualquier oponente, por lo que es muy difícil tener uno, generalmente deben ser maestros pokémon con habilidades en el combate cuerpo a cuerpo."),
    CartItem(id:25, Strength: 300, Image: 'assets/blobs/Charmeleon.png', Name:"Charmeleon", Type: "Tipo: Fuego", Attacks: "Ataques: Fuego dragón, Colmillo ígneo, Arañazo.", Description: "Reseña: Lagarto bípedo de color rojo oscuro y rojo claro, vive en zonas rocosas o volcanosas."),
    CartItem(id:26, Strength: 230, Image: 'assets/blobs/Taurus.png', Name:"Taurus", Type: "Tipo: Tierra", Attacks: "Ataques: Placaje, Earthquake.", Description: "Reseña: El pokémon toro. Generalmente violento, vive en manadas. Es un pokémon con mucha resistencia"),
    CartItem(id:27, Strength: 140, Image: 'assets/blobs/Pinsir.png', Name:"Pinsir", Type: "Tipo: Hierba, Insecto", Attacks: "Ataques: Apriete, Tijera, Picadura, Golpe Roca.", Description: "Reseña: Es un pokémon insecto que habita en bosques con aroboles de sabia, son agresivos y territoriales, poseen largos cuernos en forma de pinzas que puede apretar con dureza."),
    CartItem(id:28, Strength: 250, Image: 'assets/blobs/Golem.png', Name:"Golem", Type: "Tipo: Roca", Attacks: "Ataques: Ataque rápido, Bofetón lodo, Avalancha.", Description: "Reseña: De coraza dura capaz de resistir impactos de dinamita sin daño alguno."),
    CartItem(id:29, Strength: 220, Image: 'assets/blobs/Graveler.png', Name:"Graveler", Type: "Tipo: Roca", Attacks: "Ataques: Ataque rápido, Bofetón lodo, Avalancha.", Description: "Reseña: Su nombre viene de la grava, de coraza extremadamente dura puede girar en forma de avalancha."),
    CartItem(id:30, Strength: 250, Image: 'assets/blobs/Rhyhorn.png', Name:"Rhyhorn", Type: "Tipo: Roca, Tierra", Attacks: "Ataques: Derribo, Demolición.", Description: "Reseña: Rinoceronte de roca que choca todo lo que se le cruce. Sin miedo podría atravezar un bloque de acero."),
    CartItem(id:31, Strength: 400, Image: 'assets/blobs/Exeggutor.png', Name:"Exeggutor", Type: "Tipo: Psíquico, Hierba", Attacks: "Ataques: Ataque psíquico, Rayo psíquico, Esporas", Description: "Reseña: Pokémon con apariencia de palmera y tres cabezas. Suele vivir en junglas o bosques del trópico. Son organizados y viven en tribus. Cada una de sus cabezas tiene su propia personalidad."),
    CartItem(id:32, Strength: 220, Image: 'assets/blobs/Exegcute.png', Name:"Exeggcute", Type: "Tipo: Psíquico, Hierba", Attacks: "Ataques: Ataque Psíquico, Esporas", Description: "Reseña: Son 6 huevos que nunca se separan, son un solo pokémon. Tienen poderes psíquicos de gran ratio."),
    CartItem(id:33, Strength: 40, Image: 'assets/blobs/Venonat.png', Name: "Venonat", Type: "Tipo: Insecto", Attacks: "Ataques: Tackle, Azote", Description: "Reseña: Conocido como el mosquito venenoso, es un pokémon nocturno que por la noche le atrae la luz. Es un pokémon ágil con ojos de mosca e infrarroja."),
    CartItem(id:34, Strength: 100, Image: 'assets/blobs/Togepi.png', Name:"Togepi", Type: "Tipo: Psíquico", Attacks: "Ataques: ", Description: "Reseña: El pokémon huevo. Es realmente raro ver uno. Se dice que el tener uno, aunque este no haya salido del cascarón, traerá puros buenos augurios, paz y prosperidad. Cuando Togepi rompe su cascarón nunca lo abandona. No se sabe si tiene relación con sus poderes psíquicos, pero estos son de un nivel superdotado, aunque pocas veces utilizados."),
    CartItem(id:35, Strength: 10, Image: 'assets/blobs/Meowth.png', Name:"Meowth", Type: "Tipo: Normal", Attacks: "Ataques: Arañazo, Día de Pago", Description: "Reseña: El pokémon gato. Es un pokémon común, aunque el del Team Rocket tiene la habilidad de hablar idioma humano, por lo que suele ser el intermediario para entender los sentimientos de los pokémons. Es común verlo en callejones o deambulando por ciudades."),
    CartItem(id:36, Strength: 30, Image: 'assets/blobs/Wobbuffet.png', Name:"Wobbuffet", Type: "Tipo: Psíquico", Attacks: "Ataques: Metrónomo", Description: "Reseña: Es un pokémon con pocas capacidades de batalla, sin embargo, tiene poderes psíquicos de gran ratio, los cuales generalmente no sabe controlar."),
    CartItem(id:37, Strength: 30, Image: 'assets/blobs/Weezing.png', Name:"Weezing", Type: "Tipo: Veneno", Attacks: "Ataques: Ácido, Gas venenoso, Pantalla de Humo", Description: "Reseña: El pokémon ícono de James. Suelen vivir en vertederos, pantanos o ciudades industriales, siendo muy útil dado que absorve gases venenosos y gérmenes."),
    CartItem(id:38, Strength: 30, Image: 'assets/blobs/Arbok.png', Name:"Arbok", Type: "Tipo: Veneno", Attacks: "Ataques: Ácido, Agujas Venenosas, Cola dragón", Description: "Reseña: El pokémon cobra. Es el pokémon ícono de Jessie. Es capaz de asfixiar a sus oponentes ejerciendo gran fuerza de apriete con su cola."),
    CartItem(id:39, Strength: 120, Image: 'assets/blobs/Pikachu.png', Name:"Pikachu", Type: "Tipo: Trueno", Attacks: "Ataques: Impact Trueno, Attack Trueno, Cola de Hierro, Agilidad", Description: "Reseña: El ratón eléctrico. Es un pokémon muy ágil y con gran capacidad de generar corriente con sus los dos polos que tiene marcados en sus mejillas. Son pokémon de gran carácter, difíciles de amaestrar. Pero a la vez son muy fieles y buenos compañeros."),
    CartItem(id:40, Strength: 30, Image: 'assets/blobs/Farfetchd.png', Name:"Farfetch'd", Type: "Tipo: Normal, Volador", Attacks: "Ataques: Golpe crítico", Description: "Reseña: No suelta su cebollín. Lo usa para defenderse cuando se siente amenazado. En un pokémon inteligente y ágil."),
    CartItem(id:41, Strength: 70, Image: 'assets/blobs/Squirtle.png', Name:"Squirtle", Type: "Tipo: Agua", Attacks: "Ataques: Hidrochorro, Chorro de Agua, Burbujas", Description: "Reseña: El pokémon tortuga. Es un pokémon muy amigable y con gran capacidad de adaptación."),
    CartItem(id:42, Strength: 70, Image: 'assets/blobs/Horsea.png', Name:"Horsea", Type: "Tipo: Agua", Attacks: "Ataques: Chorro de Agua, Ataque de tinta, Hidrobomba.", Description: "Reseña: Pokémon del tipo dragón, que se asemeja a un caballo de mar."),
    CartItem(id:43, Strength: 70, Image: 'assets/blobs/Seel.png', Name:"Seel", Type: "Tipo: Agua", Attacks: "Ataques: Chorro de Agua, Hiperrayo", Description: "Reseña: El pokémon foca. Tiene un cuerno en su cabeza con el cual puede lanzar rayos de hielo."),
    CartItem(id:44, Strength: 50, Image: 'assets/blobs/Starmie.png', Name:"Starmie", Type: "Tipo: Agua", Attacks: "Ataques: Chorro de Agua, Hidrochorro, Ataque de estrellas", Description: "Reseña: El pokémon estrella de mar de 10 puntas. Evolución de Staryu. Su cuerpo tiene en su centro, una joya roja rodeada de una coraza dorada."),
    CartItem(id:45, Strength: 50, Image: 'assets/blobs/Staryu.png', Name:"Staryu", Type: "Tipo: Agua", Attacks: "Ataques: Chorro de Agua, Hidrochorro, Ataque de estrella", Description: "Reseña: El pokémon estrella de mar de 5 puntas. Su cuerpo tiene en su centro, una joya roja rodeada de una coraza dorada."),
    CartItem(id:46, Strength: 300, Image: 'assets/blobs/Tentacruel.png', Name:"Tentacruel", Type: "Tipo: Agua, Veneno", Attacks: "Ataques: Bomba ácida, Hidrobomba, Onda tóxica", Description: "Reseña: Evolución de Tentacool. Es conocido como el gangster del mar. Tiene aproximadamente 90 tentáculos, los cuales puede alargar para atacar a su presa, con un gran pico lleno de veneno con el cual destruye a sus víctimas. Es de cuerpo gelatinoso por lo cual es difícil de ser atacado en el combate cuerpo a cuerpo."),
    CartItem(id:47, Strength: 200, Image: 'assets/blobs/Tentacool.png', Name:"Tentacool", Type: "Tipo: Agua, Veneno", Attacks: "Ataques: Picotazo Veneno, Hidropulso, Rayo burbuja, Rayo solar", Description: "Reseña: Es un pokémon híbrido entre meduza y pulpo. Su cuerpo está compuesto de Agua y Veneno. Tiene unas joyas rojas en su cabeza, con los cuales puede reflejar los rayos del sol creando unos rayos solares high level. Son pokémons comunes en el oceano, pero difíciles de avistar, dado que generalmente el que los ve, yace frente a ellos."),
    CartItem(id:48, Strength: 300, Image: 'assets/blobs/Seadra.png', Name:"Seadra", Type: "Tipo: Agua", Attacks: "Ataques: Hidrochorro, Rayo Burbuja, Ataque de Tinta", Description: "Reseña: El pokémon caballo de mar. Es de clase dragón. Es un pokémon muy hábil, rápido, inteligente y con gran agilidad dentro del agua."),
    CartItem(id:49, Strength: 400, Image: 'assets/blobs/Gyarados.png', Name:"Gyarados", Type: "Tipo: Agua", Attacks: "Ataques: Hidrochorro, Hiperrayo, Embestida", Description: "Reseña: De clase dragón marino. Es un pokémon extremadamente agresivo y territorial."),
    CartItem(id:50, Strength: 300, Image: 'assets/blobs/Cloyster.png', Name:"Cloyster", Type: "Tipo: Agua, Veneno", Attacks: "Ataques: Hidrobomba, Explosión de roca, Golpe Coraza", Description: "Reseña: Con coraza más dura que el diamante, vive en corrientes torrentosas apegándose fuertemente a las rocas. Dicen que mientras más heridas se haga, más pinchos le saldrán. Es un pokémon de poca crianza, dado que vive en corrientes fuertes, pero su alimento predilecto siguen siendo las colas de Slowpoke."),
    CartItem(id:51, Strength: 40, Image: 'assets/blobs/Shellder.png', Name:"Shellder", Type: "Tipo: Agua, Veneno", Attacks: "Ataques: Rayo burbuja, hidropulso", Description: "Reseña: El pokémon ostra. Siempre anda con su lengua afuera."),
    CartItem(id:52, Strength: 200, Image: 'assets/blobs/Slowking.png', Name:"Slowking", Type: "Tipo: Agua, Psíquico", Attacks: "Ataques: Hidrobomba, Confusión, Hiperrayo", Description: "Reseña: Evoluciona cuando estando con una roca del rey y Shellder le muerde la cola. Nadie ha identificado la raíz de como se genera su evolución. Pero se cree que es un acuerdo que hacen ambos pokémon para ganar equilibrio y poder movilizarse fuera del mar. Aunque la inteligencia de Slowpoke crece considerablemente con su evolución. Es una de las dos posibles evoluciones de Slowpoke"),
    CartItem(id:53, Strength: 180, Image: 'assets/blobs/Slowbro.png', Name:"Slowbro", Type: "Tipo: Agua, Psíquico", Attacks: "Ataques: Hidrobomba, Confusión, Hiperrayo", Description: "Reseña: Evoluciona cuando Shellder le muerde la cola. Nadie ha identificado la raíz de como se genera su evolución. Pero se cree que es un acuerdo que hacen ambos pokémon para ganar equilibrio y poder movilizarse fuera del mar. Aunque la inteligencia de Slowpoke crece considerablemente con su evolución. Es una de las dos posibles evoluciones de Slowpoke"),
    CartItem(id:54, Strength: 300, Image: 'assets/blobs/Lapras.png', Name:"Lapras", Type: "Tipo: Agua, Hielo", Attacks: "Ataques: Hiperrayo, Rayo de Hielo, Hidrobomba, Telepatía", Description: "Reseña: Este pokémon está basado en un plesiosauro. Es un pokémon extremadamente fuerte pero muy difícil de avistar. Generalmente viven en el ártico."),
    CartItem(id:55, Strength: 400, Image: 'assets/blobs/Blastoise.png', Name:"Blastoise", Type: "Tipo: Agua ", Attacks: "Ataques: Hidrobomba", Description: "Reseña: La tortuga suprema. Es evolución de Wartortle. Es de los pokémons más fuertes y rápidos del mundo pokémon."),
    CartItem(id:56, Strength: 200, Image: 'assets/blobs/Wartortle.png', Name:"Wartortle", Type: "Tipo: Agua ", Attacks: "Ataques: Hidrobomba, Chorro de Agua", Description: "Reseña: Evolución de Squirtle. Es un pokémon tortuga muy misterioso."),
    CartItem(id:57, Strength: 250, Image: 'assets/blobs/Golduck.png', Name:"Golduck", Type: "Tipo: Agua, Psíquico", Attacks: "Confusión, Pistola de Agua, Hidrobomba, Rayo hielo, Ataque psíquico", Description: "Reseña: El pokémon pokémon pato. La evolución de psydock.Es un pokémon elegante y extremadamente fuerte y superdotado. Su debilidad son las bellas mujeres."),
    CartItem(id:58, Strength: 100, Image: 'assets/blobs/Psyduck.png', Name:"Psyduck", Type: "Tipo: Agua, Psíquico", Attacks: "", Description: "Reseña: El pokémon pato. Es un pokémon extremadamente fuerte en lo que poderes psíquicos trata. Sin embargo su personalidad es algo distraida por lo que generalmente no sabe usarlos al 100%.."),
    CartItem(id:59, Strength: 200, Image: 'assets/blobs/Kingler.png', Name:"Kingler", Type: "Tipo: Agua ", Attacks: "Ataques: Hiperrayo, burbujas, Golpe Martillo, Prisión Tenaza", Description: "Reseña: El pokémon cangrejo. Es muy fuerte y sus tenazas, duras como el acero, son las más fuertes del mundo pokémon. Suele vivir en la costa, cercano a acantilados, o en el fondo marino."),
    CartItem(id:60, Strength: 70, Image: 'assets/blobs/Krabby.png', Name:"Krabby", Type: "Tipo: Agua ", Attacks: "Ataques: Burbujas, Golpe Martillo, Prisión Tenaza", Description: "Reseña: El pokémon cangrejo. Es muy fuerte y resistente. Suele vivir en la costa, cercano a acantilados, o en el fondo marino."),
    CartItem(id:61, Strength: 300, Image: 'assets/blobs/Heracross.png', Name:"Heracross", Type: "Tipo: Insecto, Lucha", Attacks: "Ataques: Golpe Cuerno", Description: "Reseña: Es un pokémon muy fuerte y hábil y de gran resistencia, gracias a una fuerte coraza que lo protege. Generalmente vive entre insectos y pasa gran parte de su día bebiendo sabia."),
    CartItem(id:62, Strength: 10, Image: 'assets/blobs/Parasect.png', Name:"Parasect", Type: "Tipo: Insecto, Hierba", Attacks: "Ataques: Esporas", Description: "Reseña: Su nombre proviene del parásito. Tiene un gran hongo en su espalda con grandes poderes curativos. Vive en bosques frondosos o cuevas aledañas."),
    CartItem(id:63, Strength: 10, Image: 'assets/blobs/Paras.png', Name:"Paras", Type: "Tipo: Insecto, Hierba", Attacks: "Ataques: Esporas", Description: "Reseña: Su nombre proviene del parásito que desempolló con un huevo en la espalda. Evoluciona en Parasect."),
    CartItem(id:64, Strength: 10, Image: 'assets/blobs/Chansey.png', Name:"Chansey", Type: "Tipo: Normal", Attacks: "Ataques: Curación", Description: "Reseña: La pokémon enfermera. Es fiel compañera de la enfermera Joy. Tiene excelentes dotes curativos."),
    CartItem(id:65, Strength: 70, Image: 'assets/blobs/Clefable.png', Name:"Clefable", Type: "Tipo: Hada", Attacks: "Ataques: Brillo mágico, fuerza lunar, Puño meteoro, Metrónomo", Description: "Reseña: Se dice que vienen del espacio. Ellas generan un campo magnético a su al rededor al mover sus brazos. Son pokémon nocturnos y muy difíciles de ver. Le suelen hacer ceremonias a la luna."),
    CartItem(id:66, Strength: 160, Image: 'assets/blobs/Clefairy.png', Name:"Clefairy", Type: "Tipo: Hada", Attacks: "Ataques: Fuerza lunar, Golpe cuerpo, Voz cautivadora, Metrónomo", Description: "Reseña: Se dice que vienen del espacio. Ellas generan un campo magnético a su al rededor al mover sus brazos. Son pokémon nocturnos y muy difíciles de ver. Le suelen hacer ceremonias a la luna."),
    CartItem(id:67, Strength: 400, Image: 'assets/blobs/Venasaur.png', Name:"Venasaur", Type: "Tipo: Hierba", Attacks: "Ataques: Rayo solar, Latigo Sepa, Hojas Navaja", Description: "Reseña: Es la evolución máxima del pokémon rana Bulbasaur. Logra ese nivel cuando florece el capullo de Ivysaur. Es difícil de avistar y se alimenta por fotosíntesis."),
    CartItem(id:68, Strength: 200, Image: 'assets/blobs/Ivysaur.png', Name:"Ivysaur", Type: "Tipo: Hierba", Attacks: "Ataques: Rayo solar, Latigo Sepa, Hojas Navaja", Description: "Reseña: Es la evolución de Bulbasaur. Logra conseguir ese nivel cuando la calabaza de su preevolución se convierte en un capullo. Es un pokémon extremadamente fuerte y agresivo."),
    CartItem(id:69, Strength: 120, Image: 'assets/blobs/Bulbasaur.png', Name:"Bulbasaur", Type: "Tipo: Hierba", Attacks: "Ataques: Rayo solar, Latigo Sepa, Hojas Navaja", Description: "Reseña: Es una especie de pokémon anfibio con una gran calabaza cargando en su espalda, la cual puede brotar haciendo florecer bosques y jardines frondosos."),
    CartItem(id:70, Strength: 300, Image: 'assets/blobs/Snorlax.png', Name:"Snorlax", Type: "Tipo: Normal", Attacks: "Ataques: Hiperrayo, Sumisión", Description: "Reseña: Es un pokémon extremadamente fuerte, pero muy difícil de verlo despierto. Gran parte de su vida está en proceso de hibernación, y cuando está despierto, comiendo. Generalmente vive en bosques con gran cantidad de árboles frutales."),
    CartItem(id:71, Strength: 250, Image: 'assets/blobs/Victreebel.png', Name:"Victreebel", Type: "Tipo: Hierba, Veneno", Attacks: "Ataques: Hojas Navaja, Latigo Sepa, Bomba ácida", Description: "Reseña: El pokémon planta carnívora, evolución de Weepinbell. En su interior tiene un poderoso ácido capaz de derretir cualquier alimento que ingiera."),
    CartItem(id:72, Strength: 200, Image: 'assets/blobs/Weepinbell.png', Name:"Weepinbell", Type: "Tipo: Hierba, Veneno", Attacks: "Ataques: Hojas Navaja, Latigo Sepa, Bomba ácida", Description: "Reseña: Pokémon con forma de campana evolución de Bellsprout. En su interior tiene un poderoso ácido capaz de derretir cualquier alimento que ingiera."),
    CartItem(id:73, Strength: 100, Image: 'assets/blobs/Bellsprout.png', Name:"Bellsprout", Type: "Tipo: Hierba, Veneno", Attacks: "Ataques: Hojas Navaja, Ácido", Description: "Reseña: Pokémon con forma de campana sobre un largo tallo con raíces. Bien entrenado, es un pokémon extremadamente ágil y fuerte."),
    CartItem(id:74, Strength: 120, Image: 'assets/blobs/Bulbasaur.png', Name:"Bulbasaur", Type: "Tipo: Hierba", Attacks: "Ataques: Rayo solar, Latigo Sepa, Hojas Navaja", Description: "Reseña: Es una especie de pokémon anfibio con una gran calabaza cargando en su espalda, la cual puede brotar haciendo florecer bosques y jardines frondosos."),
    CartItem(id:76, Strength: 250, Image: 'assets/blobs/Victreebel.png', Name:"Victreebel", Type: "Tipo: Hierba, Veneno", Attacks: "Ataques: Hojas Navaja, Latigo Sepa, Bomba ácida", Description: "Reseña: El pokémon planta carnívora, evolución de Weepinbell. En su interior tiene un poderoso ácido capaz de derretir cualquier alimento que ingiera."),
    CartItem(id:77, Strength: 200, Image: 'assets/blobs/Weepinbell.png', Name:"Weepinbell", Type: "Tipo: Hierba, Veneno", Attacks: "Ataques: Hojas Navaja, Latigo Sepa, Bomba ácida", Description: "Reseña: Pokémon con forma de campana evolución de Bellsprout. En su interior tiene un poderoso ácido capaz de derretir cualquier alimento que ingiera."),
    CartItem(id:78, Strength: 100, Image: 'assets/blobs/Bellsprout.png', Name:"Bellsprout", Type: "Tipo: Hierba, Veneno", Attacks: "Ataques: Hojas Navaja, Ácido", Description: "Reseña: Pokémon con forma de campana sobre un largo tallo con raíces. Bien entrenado, es un pokémon extremadamente ágil y fuerte."),
    CartItem(id:79, Strength: 280, Image: 'assets/blobs/Scizor.png', Name:"Scizor", Type: "Tipo: Bicho, Acero", Attacks: "Ataques: Corte Furia, Cabeza de Hierro, Puño Bala", Description: "Reseña: El pokémon Mantis Religiosa de Acero. Tiene unas poderosas pinzas en vez de manos. Es un pokémon temible, aunque con un temperamento mucho más llevadero que el de su pre-evolución."),
    CartItem(id:75, Strength: 250, Image: 'assets/blobs/Scyther.png', Name:"Scyther", Type: "Tipo: Bicho, Volador", Attacks: "Ataques: Corte Furia, Tajo Aéreo, Ala de acero, Zumbido", Description: "Reseña: El pokémon Mantis Religiosa. Tiene unas largas y filosas cuchillas de brazos y unas poderosas alas para moverse con gran agilidad y velocidad. Es el pokémon más temido en el combate cuerpo a cuerpo. Es también conocido como <<El pokémon Ninja>>."),
    CartItem(id:76, Strength: 300, Image: 'assets/blobs/Nidoqueen.png', Name:"Nidoqueen", Type: "Tipo: Nidoqueen", Attacks: "Ataques: ", Description: "Reseña: ."),
    CartItem(id:77, Strength: 150, Image: 'assets/blobs/Nidorina.png', Name:"Nidorina", Type: "Tipo: Veneno", Attacks: "Ataques: Picotazo Venenoso, Bomba lodo, Mordisco, Retribución", Description: "Reseña: El pokémon rinoceronte. Suelen vivir en praderas. Se cree que alguna vez tuvo un cuerno en su frente que lo perdió para no dañar a sus crías."),
    CartItem(id:78, Strength: 70, Image: 'assets/blobs/Nidoran♀.png', Name:"Nidoran♀", Type: "Tipo: Veneno", Attacks: "Ataques: Picadura Venenosa, Bomba lodo, Mordedura", Description: "Reseña: La pokémon rata. Es la hembra de su compañero Nidoran ♂. Tiene unas púas extremadamente venenosas y es capaz de liberar una sustancia totalmente tóxica cuando se siente intimidada."),
    CartItem(id:79, Strength: 350, Image: 'assets/blobs/Nidoking.png', Name:"Nidoking", Type: "Tipo: Tierra, Veneno", Attacks: "Ataques: Puya nociva, Earthquake, Doble patada, Tierra viva, Corte furia, Cola férrea, Megacuerno, Onda tóxica", Description: "Reseña: Con una poderosa coraza, es un pokémon intimidante. Suele no alejarse de su nido familiar, y es muy difícil que sea amaestrado. Generalmente los maestros que tienen uno, lo criaron desde Nidoran."),
    CartItem(id:80, Strength: 150, Image: 'assets/blobs/Nidorino.png', Name:"Nidorino", Type: "Tipo: Veneno", Attacks: "Ataques: Puya nociva, Bomba lodo, Picotazo venenoso, Cornada, Retribución", Description: "Reseña: El pokémon rinoceronte. Suelen vivir en praderas y es pareja de Nidorina. Con poderosas puas en su espalda, son pokémon realmente agresivos y territoriales."),
    CartItem(id:81, Strength: 70, Image: 'assets/blobs/Nidoran♂.png', Name:"Nidoran♂", Type: "Tipo: Veneno", Attacks: "Ataques: Picotazo Venenoso, Bomba lodo, Mordisco, Retribución", Description: "Reseña: Es pareja de Nidoran♀. Tiene un poderoso cuerno en su frente que usa para embestir y poderosas puas en su espalda para protegerse. Mientras más grande sea su cuerno, más venenosa será su capacidad."),
    CartItem(id:82, Strength: 250, Image: 'assets/blobs/Rapidash.png', Name:"Rapidash", Type: "Tipo: Fuego", Attacks: "Ataques: Giro fuego, Llamarada, Ascuas, Retribución, Patada Baja", Description: "Reseña: El pokémon caballo unicornio de fuego. Es uno de los pokémon más rápidos y con mayor aceleración que existen."),
    CartItem(id:83, Strength: 250, Image: 'assets/blobs/Primeape.png', Name:"Primeape", Type: "Tipo: Lucha", Attacks: "Ataques: Contraataque, A bocajarro, Golpe Karate, Tajo cruzado, Tajo umbreo, Patada baja", Description: "Reseña: El pokémon primate sin cola. Tiene unos grilletes para contener su fuerza y velocidad para pelear. Tiene un fuerte temperamento y si lo haces enojar, te perseguirá hasta destruirte."),
    CartItem(id:84, Strength: 100, Image: 'assets/blobs/Mankey.png', Name:"Mankey", Type: "Tipo: Lucha", Attacks: "Ataques: Golpe Karate, Arañazo, Tajo Cruzado, Demolición, Puntapié", Description: "Reseña: El pokémon mono. Es realmente colérico y temperamental. No es recomendable acercársele, sobre todo si no está cerca de su manada."),
    CartItem(id:85, Strength: 120, Image: 'assets/blobs/Dodrio.png', Name:"Dodrio", Type: "Tipo: Normal", Attacks: "Ataques: Ala de acero, Finta, Pájaro osado, Pico Taladro, Golpe aéreo, Aire afilado", Description: "Reseña: El pokémon ñandú de 3 cabezas. Cada una de sus 3 cabezas representa una personalidad, la tristeza, la dicha y la ira. A menudo suelen llevarse mal, pudiendo pasar atacándose todo el día entre ellas. Es un pokémon muy veloz y audaz."),
    CartItem(id:86, Strength: 50, Image: 'assets/blobs/Doduo.png', Name:"Doduo", Type: "Tipo: Normal", Attacks: "Ataques: Ataque rápido, Picotazo, Pájaro Osado, Ataque rápido", Description: "Reseña: El pokémon ñandú de 2 cabezas. Es un pokémon cazador y de mal carácter."),
    CartItem(id:87, Strength: 50, Image: 'assets/blobs/Noctowl.png', Name:"Noctowl", Type: "Tipo: Volador", Attacks: "Ataques: Ataque ala, Bola Sombra, Ataque aéreo, Tinieblas, Paranormal", Description: "Reseña: El pokémon buho."),
    CartItem(id:88, Strength: 80, Image: 'assets/blobs/Sandslash.png', Name:"Sandslash", Type: "Tipo: Tierra", Attacks: "Ataques: Disparo lodo, Garra metal, Earthquake, Retribución, Tajo umbrio, Tumba rocas", Description: "Reseña: Con coraza de espuas, Sandslash es un pokémon cuerpoespín que vive en zonas áridas. Es cazador, agresivo, pero si se ve sobrepasada huye haciendo tormentas de arena y escondiéndose bajo tierra."),
    CartItem(id:89, Strength: 30, Image: 'assets/blobs/Sandshrew.png', Name:"Sandshrew", Type: "Tipo: Tierra", Attacks: "Ataques: Disparo lodo, Arañazo, Avalancha, Bucle Arena, Retribución", Description: "Reseña: El pokémon armadillo. Cuenta con una coraza muy dura que utiliza como sistema de defensa haciéndose bolita hasta que pase el peligro."),
    CartItem(id:90, Strength: 300, Image: 'assets/blobs/Pidgeot.png', Name:"Pidgeot", Type: "Tipo: Volador", Attacks: "Ataques: Ala de acero, Ataque ráfaga, Danza pluma, Pájaro osado", Description: "Reseña: Ave de varios metrosd de altura, es capaz de superar la velocidad de los 10 match. Es un pokémon solitario y no vivie en bandadas."),
    CartItem(id:91, Strength: 100, Image: 'assets/blobs/Pidgeotto.png', Name:"Pidgeotto", Type: "Tipo: Volador", Attacks: "Ataques: Ataque ráfaga, Ataque ala, Punta de Acero", Description: "Reseña: De clase ave, es un pokémon que alcanza grandes velocidad y alturas de vuelo y ver a su preza a kilometros de distancia. Sus principales prezas son Exeggcute, Magicarp o pokémons gusanos."),
    CartItem(id:92, Strength: 20, Image: 'assets/blobs/Pidgey.png', Name:"Pidgey", Type: "Tipo: Volador", Attacks: "Ataques: Ataque rápido, Placaje", Description: "Reseña: Vive en bandadas en bosques frondozos. Es un pokémon débil con respecto a sus fuertes evoluciones. Incluso en algunas islas son tan gordos que han perdido su capacidad de volar."),
    CartItem(id:93, Strength: 60, Image: 'assets/blobs/Electrode.png', Name:"Electrode", Type: "Tipo: Trueno", Attacks: "Ataques: Voltiocambio, chispa, placaje, juego sucio, hiperrayo", Description: "Reseña: El pokémon bomba. Es asexuado y tiene apariencia de pokéboll, solo que con los colores invertidos. Suelen agruparse en bandas dntro de centros urbanos o plantas eléctricas causando disturbios y apagones eléctricos."),
    CartItem(id:94, Strength: 40, Image: 'assets/blobs/Voltorb.png', Name:"Voltorb", Type: "Tipo: Trueno", Attacks: "Ataques: Chispa, Placaje, Rayo, Giro, Doble rayo", Description: "Reseña: El pokémon bomba. Es asexuado y tiene apariencia de pokéboll, solo que con los colores invertidos. Suelen agruparse en bandas dntro de centros urbanos o plantas eléctricas causando disturbios y apagones eléctricos."),
    CartItem(id:95, Strength: 120, Image: 'assets/blobs/Magneton.png', Name:"Magneton", Type: "Tipo: Trueno, Acero", Attacks: "Ataques: Impactrueno, Electrocañón, Rayo carga, Bomba imán, Retribución", Description: "Reseña: Cuando el magnetismo de Magnemite se hace muy poderoso, evolucionan juntándose en grupos de 3 naciendo Magnetón. Estudios dicen que se vuelven en un solo pokémon, su mente se fusiona en una."),
    CartItem(id:96, Strength: 70, Image: 'assets/blobs/Magnemite.png', Name:"Magnemite", Type: "Tipo: Trueno, Acero", Attacks: "Ataques: Impactrueno, Rayo, Bomba imán, Retribución", Description: "Reseña: El pokémon imán. En su núcleo tiene un ojo y en sus costados dos imanes. Su magnetismo es capaz de atraer objetos a cientos de metros de distancia."),
    CartItem(id:97, Strength: 70, Image: 'assets/blobs/Ditto.png', Name:"Ditto", Type: "Tipo: Normal", Attacks: "Ataques: Transformación, Combate", Description: "Reseña: El pokémon metamorfo. Capaz de tomar la apariencia de cualquier pokémon que vea. Incluso sus poderes, aunque con un menos nivel de poder."),
    CartItem(id:98, Strength: 150, Image: 'assets/blobs/Muk.png', Name:"Muk", Type: "Tipo: Veneno", Attacks: "Ataques: Ácido, Languetazo, Sumisión, Onda tóxica, Lanzamugre, Retribución", Description: "Reseña: La pokémon mutante. Se dice que se creó a partir de desechos tóxicos y es realmente fétido, más aun que su predesesor Grimer. Suelen vivir en alcantarillas. Es un pokémon realmente tóxico. Incluso la estela que deja a su paso es venenosa."),
    CartItem(id:99, Strength: 50, Image: 'assets/blobs/Grimer.png', Name:"Grimer", Type: "Tipo: Veneno", Attacks: "Ataques: Ácido, Bomba lodo, Bofetón lodo, Residuos, Retribución", Description: "Reseña: La pokémon mutante. Se dice que se creó a partir de desechos tóxicos y es realmente fétido. Suelen vivir en alcantarillas. Es un pokémon realmente tóxico. Incluso la estela que deja a su paso es venenosa."),
    CartItem(id:100, Strength: 180, Image: 'assets/blobs/Machamp.png', Name:"Machamp", Type: "Tipo: Lucha", Attacks: "Ataques: Contraataque, Golpe karate, Puño bala, Roca afilada, Retribución", Description: "Reseña: El luchador de cuatro brazos. Tiene una velocidad para los puñetazos única en el mundo pokémon."),
    CartItem(id:101, Strength: 100, Image: 'assets/blobs/Machoke.png', Name:"Machoke", Type: "Tipo: Lucha", Attacks: "Ataques: Golpe karate, Puño dinámico, Patada baja, Tajo cruzado, Demolición, Sumisión, Retribución", Description: "Reseña: El pokémon físicoculturista. Es capaz de levantar miles de kilogramos con tan solo una mano."),
    CartItem(id:102, Strength: 70, Image: 'assets/blobs/Machop.png', Name:"Machop", Type: "Tipo: Lucha", Attacks: "Ataques: Golpe karate, Golpe roca, Tajo cruzado, Demolición, Retribución", Description: "Reseña: Es un pokémon híbrido entre humano y tiburón. Es un pokémon extremadamente fuerte y rápido. Además de ser una eminencia en artes marciales."),
    CartItem(id:103, Strength: 300, Image: 'assets/blobs/Arcanine.png', Name:"Arcanine", Type: "Tipo: Fuego", Attacks: "Ataques: Colmillo igneo, Alarido, Mordisco, Lanzallamas, Llamarada, Terratembor, Retribución", Description: "Reseña: Alguna vez fue considerado un pokémon legendario, utilizado por las primeras civilizaciones para alejar los malos espíritus. Con los años se fueron multiplicando. Son pokémon muy inteligentes y con gran ímpetu por ayudar ser un aporte para la sociedad."),
    CartItem(id:104, Strength: 100, Image: 'assets/blobs/Growlithe.png', Name:"Growlithe", Type: "Tipo: Fuego", Attacks: "Ataques: Ascuas, Lanzallamas, Mordisco, Retribución, Golpe cuerpo", Description: "Reseña: Pokémon híbrido entre león y perro de fuego. Está en su ADN el ayudar al prójimo, tanto así, que muchas veces forman parte de las brígadas de rescate de los cuerpos de bomberos."),
    CartItem(id:105, Strength: 300, Image: 'assets/blobs/Mr.Mime.png', Name:"Mr. Mime", Type: "Tipo: Psíquico", Attacks: "Ataques: Pantomima, Confusión, Psicorrayo, Cabezazo Zen, Retribución", Description: "Reseña: El pokémon mimo. Capaz de crear poderosas barreras e incluso usarlas como ataques. Es un pokémon tranquilo y a menudo es visto viviendo en sociedad."),
  ];

  EncartaPage({super.key});

  @override
  Widget build(BuildContext context) {
    return ListView.separated(
        itemBuilder: (BuildContext context, int index) {
          return _CartItem(cartItems[index]);
        },
        separatorBuilder: (BuildContext context, int index) => const Divider(
          height: 10,
        ),
        itemCount: cartItems.length);
  }
}

class _CartItem extends StatelessWidget {
  final CartItem cartItem;

  const _CartItem(this.cartItem);

  @override
  Widget build(BuildContext context) {
    return Container(
      margin: const EdgeInsets.all(15.0),
      padding: const EdgeInsets.all(3.0),
      decoration: BoxDecoration(
          border: Border.all(color:Colors.redAccent)
      ),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          Text("Poder de Pelea:${cartItem.Strength}"),
          Image.asset(cartItem.Image, width: 120, height: 120,),
          Text(cartItem.Name),
          Text(cartItem.Type),
          Text(cartItem.Attacks),
          Text(cartItem.Description),
        ],
      ),
    );
  }
}